name: "[main] CI/CD Author_Elastic_CRUD_API"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: CI Step
        shell: bash
        run: "echo skipping ci/cd until variables are present"

      - name: Declare Variables
        id: vars
        shell: bash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.CR_REGISTRY_URL }}
          username: ${{ secrets.CR_USERNAME }} # Best practice is to use ${{ secrets. }}
          password: ${{ secrets.CR_PASSWORD  }} # Best practice is to use ${{ secrets. }}

      - name: auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: auth-gke
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: '${{ secrets.CLUSTER_NAME }}'
          location: '${{ secrets.CLUSTER_LOCATION }}'

      - name: Build and Publish Producer Docker Image
        uses: docker/build-push-action@v2
        with:
          file: ./Producer/Dockerfile
          push: true
          tags: ${{ secrets.CR_REGISTRY_URL }}/authores-producer:${{ steps.vars.outputs.sha_short }},${{ secrets.CR_REGISTRY_URL }}/authores-producer:latest

      - name: Build and Publish Consumer Docker Image
        uses: docker/build-push-action@v2
        with:
          file: ./Consumer/Dockerfile
          push: true
          tags: ${{ secrets.CR_REGISTRY_URL }}/authores-consumer:${{ steps.vars.outputs.sha_short }},${{ secrets.CR_REGISTRY_URL }}/authores-consumer:latest

      - name: Update Kubernetes Deployment
        run: |-
          kubectl -n itechops-dev set image deployment/authores-api producer=${{ secrets.CR_REGISTRY_URL }}/authores-producer:${{ steps.vars.outputs.sha_short }} consumer=${{ secrets.CR_REGISTRY_URL }}/authores-consumer:${{ steps.vars.outputs.sha_short }}